# Generated by Django 4.2.7 on 2025-07-11 18:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'فئة المنتج',
                'verbose_name_plural': 'فئات المنتجات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود المنتج')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='الباركود')),
                ('product_type', models.CharField(choices=[('product', 'منتج'), ('service', 'خدمة'), ('raw_material', 'مادة خام')], default='product', max_length=20, verbose_name='نوع المنتج')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='صورة المنتج')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='سعر التكلفة')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='سعر البيع')),
                ('min_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='أقل سعر بيع')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المخزون الحالي')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى للمخزون')),
                ('max_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأقصى للمخزون')),
                ('track_stock', models.BooleanField(default=True, verbose_name='تتبع المخزون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('allow_negative_stock', models.BooleanField(default=False, verbose_name='السماح بالمخزون السالب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الوحدة')),
                ('symbol', models.CharField(max_length=10, verbose_name='رمز الوحدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'وحدة القياس',
                'verbose_name_plural': 'وحدات القياس',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'دخول'), ('out', 'خروج'), ('adjustment', 'تعديل'), ('transfer', 'نقل')], max_length=20, verbose_name='نوع الحركة')),
                ('movement_reason', models.CharField(choices=[('purchase', 'شراء'), ('sale', 'بيع'), ('return_in', 'مرتجع شراء'), ('return_out', 'مرتجع بيع'), ('adjustment', 'تعديل مخزون'), ('damage', 'تلف'), ('expired', 'انتهاء صلاحية'), ('transfer', 'نقل'), ('opening_balance', 'رصيد افتتاحي')], max_length=20, verbose_name='سبب الحركة')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي التكلفة')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='رقم المرجع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('stock_before', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المخزون قبل الحركة')),
                ('stock_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المخزون بعد الحركة')),
                ('movement_date', models.DateTimeField(verbose_name='تاريخ الحركة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='المنشئ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.unit', verbose_name='الوحدة'),
        ),
    ]
